using Edi.Domain.Shared.Attributes;
using Edi.Domain.Shared.Enums;
using FluentValidation.Results;
using indice.Edi.Serialization;

namespace module.Edi.Poco.X12_4010.Segments
{
    [EdiSegment]
    [EdiPath("IT8")]
    public class IT8 //: IEdiValidation<IT8>
    {
        [EdiValue("X(2)", Path = "IT8/0", Description = "IT801 - Sales Requirement Code")]
        [EdiExtension(MinLength = 1, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "B", "C", "D", "E", "F", "K", "N", "O", "P", "Q", "R", "S", "T", "W", "Y", "Z", "8A", "AI", "AS", "BC", "BK", "EI", "FT", "GS", "IP", "IS", "LS", "MY", "NS", "P2", "P3", "P4", "QB", "QE", "QI", "QM", "QP", "SC", "SE", "SF", "SG", "SI", "SP", "SQ", "SS", "ST", "SU", "SV", "SW", "UC", "UL", "UP", "WY", "YI" })]

        public string SalesRequirementCode { get; set; }

        [EdiValue("X(2)", Path = "IT8/1", Description = "IT802 - Action Code")]
        [EdiExtension(MinLength = 1, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "A1", "A2", "A3", "A4", "A5", "A6", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AL", "AP", "AQ", "AR", "AS", "AT", "AV", "AW", "AX", "BD", "BI", "BO", "C1", "C2", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CL", "CM", "CN", "CO", "CP", "CS", "CT", "CU", "CV", "CX", "D1", "D2", "DA", "DB", "DC", "DD", "DE", "DF", "DG", "DH", "DI", "DJ", "DK", "DL", "DP", "DR", "DS", "DT", "DX", "EA", "EB", "EC", "ED", "EE", "EN", "EP", "ER", "EV", "EX", "F1", "FA", "FC", "FI", "FO", "FR", "GR", "HR", "I1", "IA", "IM", "IN", "IS", "IT", "JA", "JO", "JU", "KA", "LC", "LQ", "ME", "MO", "NA", "ND", "NP", "NS", "OD", "OP", "OR", "OT", "P1", "PA", "PB", "PC", "PD", "PF", "PI", "PJ", "PO", "PP", "PR", "PS", "PT", "PU", "PV", "R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RQ", "RR", "RS", "RT", "RU", "RV", "RW", "RX", "S1", "S2", "SA", "SB", "SC", "SD", "SE", "SL", "SR", "SS", "SU", "SV", "SZ", "TD", "TE", "TG", "TN", "TP", "TR", "TS", "TU", "VA", "W1", "WD", "WI", "WQ", "WV" })]

        public string ActionCode { get; set; }

        [EdiValue("X(15)", Path = "IT8/2", Format = "N2", Description = "IT803 - Amount")]
        [EdiExtension(MinLength = 1, MaxLength = 15, Mandatory = false, EdiType = EdiType.Decimal)]
        public string Amount { get; set; }

        [EdiValue("X(35)", Path = "IT8/3", Description = "IT804 - Account Number")]
        [EdiExtension(MinLength = 1, MaxLength = 35, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string AccountNumber { get; set; }

        [EdiValue("X(8)", Path = "IT8/4", Format = "yyyyMMdd", Description = "IT805 - Date")]
        [EdiExtension(MinLength = 8, MaxLength = 8, Mandatory = false, EdiType = EdiType.Date)]
        public string Date { get; set; }

        [EdiValue("X(2)", Path = "IT8/5", Description = "IT806 - Agency Qualifier Code")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "10 ", "11 ", "12 ", "13 ", "14 ", "15 ", "16 ", "17 ", "18 ", "19 ", "20 ", "21 ", "22 ", "23 ", "24 ", "25 ", "26 ", "27 ", "28 ", "29 ", "30 ", "31 ", "32 ", "33 ", "34 ", "35 ", "36 ", "37 ", "38 ", "39 ", "40 ", "41 ", "42 ", "43 ", "44 ", "45 ", "46 ", "47 ", "48 ", "49 ", "50 ", "51 ", "52 ", "53 ", "54 ", "55 ", "56 ", "57 ", "58 ", "59 ", "60 ", "93 ", "94 ", "A1 ", "A2 ", "A3 ", "A4 ", "AA ", "AB ", "AC ", "AD ", "AE ", "AG ", "AH ", "AI ", "AJ ", "AL ", "AM ", "AP ", "AQ ", "AS ", "AT ", "AW ", "AX ", "AY ", "BE ", "BF ", "BI ", "CA ", "CB ", "CC ", "CE ", "CI ", "CL ", "CM ", "CO ", "CR ", "CS ", "CU ", "CX ", "DA ", "DD ", "DE ", "DF ", "DI ", "DL ", "DN ", "DO ", "DR ", "DS ", "DX ", "DY ", "DZ ", "EI ", "EP ", "ES ", "ET ", "EU ", "EX ", "FA ", "FC ", "FD ", "FG ", "FH ", "FI ", "GC ", "GS ", "GU ", "HC ", "HI ", "HS ", "HU ", "IA ", "IB ", "IC ", "IM ", "IN ", "IS ", "JA ", "LA ", "LB ", "LI ", "MA ", "MB ", "MC ", "ME ", "MI ", "MP ", "MS ", "MV ", "NA ", "NB ", "NC ", "NE ", "NF ", "NG ", "NI ", "NR ", "NS ", "NT ", "NU ", "NW ", "OI ", "OP ", "OS ", "PA ", "PC ", "SA ", "SE ", "SL ", "SP ", "ST ", "TA ", "TB ", "TC ", "TD ", "TI ", "TM ", "TP ", "TR ", "TX ", "UC ", "UN ", "VI ", "WH ", "ZZ " })]

        public string AgencyQualifierCode { get; set; }

        [EdiValue("X(2)", Path = "IT8/6", Description = "IT807 - Product/Service Substitution Code")]
        [EdiExtension(MinLength = 1, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A", "X", "Y", "B0", "B1", "B2", "B3", "B4", "ZZ" })]

        public string ProductOrServiceSubstitutionCode { get; set; }

        [EdiValue("X(2)", Path = "IT8/7", Description = "IT808 - Product Or Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = true, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier { get; set; }

        [EdiValue("X(48)", Path = "IT8/8", Description = "IT809 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = true, EdiType = EdiType.Alphanumeric)]

        public string ProductOrServiceID { get; set; }

        [EdiValue("X(2)", Path = "IT8/9", Description = "IT810 - Product Or Service ID Qualifier 02")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier02 { get; set; }

        [EdiValue("X(48)", Path = "IT8/10", Description = "IT811 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID02 { get; set; }

        [EdiValue("X(2)", Path = "IT8/11", Description = "IT812 - Product Or Service ID Qualifier 03")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier03 { get; set; }

        [EdiValue("X(48)", Path = "IT8/12", Description = "IT813 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID03 { get; set; }

        [EdiValue("X(2)", Path = "IT8/13", Description = "IT814 - Product Or Service ID Qualifier 04")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier04 { get; set; }

        [EdiValue("X(48)", Path = "IT8/14", Description = "IT815 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID04 { get; set; }

        [EdiValue("X(2)", Path = "IT8/15", Description = "IT816 - Product Or Service ID Qualifier 05")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier05 { get; set; }

        [EdiValue("X(48)", Path = "IT8/16", Description = "IT817 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID05 { get; set; }

        [EdiValue("X(2)", Path = "IT8/17", Description = "IT818 - Product Or Service ID Qualifier 06")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier06 { get; set; }

        [EdiValue("X(48)", Path = "IT8/18", Description = "IT819 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID06 { get; set; }

        [EdiValue("X(2)", Path = "IT8/19", Description = "IT820 - Product Or Service ID Qualifier 07")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier07 { get; set; }

        [EdiValue("X(48)", Path = "IT8/20", Description = "IT821 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID07 { get; set; }

        [EdiValue("X(2)", Path = "IT8/21", Description = "IT822 - Product Or Service ID Qualifier 08")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier08 { get; set; }

        [EdiValue("X(48)", Path = "IT8/22", Description = "IT823 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID08 { get; set; }

        [EdiValue("X(2)", Path = "IT8/23", Description = "IT824 - Product Or Service ID Qualifier 09")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier09 { get; set; }

        [EdiValue("X(48)", Path = "IT8/24", Description = "IT825 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID09 { get; set; }

        [EdiValue("X(2)", Path = "IT8/25", Description = "IT826 - Product Or Service ID Qualifier 10")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier10 { get; set; }

        [EdiValue("X(48)", Path = "IT8/26", Description = "IT827 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID10 { get; set; }

        public List<ValidationResult> ValidateEdi(IT8 model) {
            return new List<ValidationResult>();
        }
    }
}
