using Edi.Domain.Shared.Enums;
using indice.Edi.Serialization;
using Scm.Edi.Domain.Shared.Attributes;

namespace Edi.Application.Contracts.Poco.X12_4010.Segments
{
    [EdiSegment, EdiPath("LIN")]
    public class LIN
    {
        [EdiValue("X(2)", Path = "LIN/0", Description = "LIN01 - Assigned Identification")]
        [EdiExtension(MinLength = 1, MaxLength = 20, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string AssignedIdentification { get; set; }

        [EdiValue("X(2)", Path = "LIN/1", Description = "LIN02 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = true, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier { get; set; }

        [EdiValue("X(48)", Path = "LIN/2", Description = "LIN03 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = true, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID { get; set; }

        [EdiValue("X(2)", Path = "LIN/3", Description = "LIN04 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier02 { get; set; }

        [EdiValue("X(48)", Path = "LIN/4", Description = "LIN05 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID02 { get; set; }

        [EdiValue("X(2)", Path = "LIN/5", Description = "LIN06 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier03 { get; set; }

        [EdiValue("X(48)", Path = "LIN/6", Description = "LIN07 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID03 { get; set; }

        [EdiValue("X(2)", Path = "LIN/7", Description = "LIN08 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier04 { get; set; }

        [EdiValue("X(48)", Path = "LIN/8", Description = "LIN09 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID04 { get; set; }

        [EdiValue("X(2)", Path = "LIN/9", Description = "LIN10 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier05 { get; set; }

        [EdiValue("X(48)", Path = "LIN/10", Description = "LIN11 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]

        public string ProductOrServiceID05 { get; set; }

        [EdiValue("X(2)", Path = "LIN/11", Description = "LIN12 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier06 { get; set; }

        [EdiValue("X(48)", Path = "LIN/12", Description = "LIN13 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID06 { get; set; }

        [EdiValue("X(2)", Path = "LIN/13", Description = "LIN14 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier07 { get; set; }

        [EdiValue("X(48)", Path = "LIN/14", Description = "LIN15 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID07 { get; set; }

        [EdiValue("X(2)", Path = "LIN/15", Description = "LIN16 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier08 { get; set; }

        [EdiValue("X(48)", Path = "LIN/16", Description = "LIN17 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID08 { get; set; }

        [EdiValue("X(2)", Path = "LIN/17", Description = "LIN18 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier09 { get; set; }

        [EdiValue("X(48)", Path = "LIN/18", Description = "LIN19 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID09 { get; set; }

        [EdiValue("X(2)", Path = "LIN/19", Description = "LIN20 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier10 { get; set; }

        [EdiValue("X(48)", Path = "LIN/20", Description = "LIN21 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID10 { get; set; }

        [EdiValue("X(2)", Path = "LIN/21", Description = "LIN22 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        public string ProductOrServiceIDQualifier11 { get; set; }

        [EdiValue("X(48)", Path = "LIN/22", Description = "LIN23 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceID11 { get; set; }

        [EdiValue("X(2)", Path = "LIN/23", Description = "LIN24 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        public string ProductOrServiceIDQualifier12 { get; set; }

        [EdiValue("X(48)", Path = "LIN/24", Description = "LIN25 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceID12 { get; set; }

        [EdiValue("X(2)", Path = "LIN/25", Description = "LIN26 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier13 { get; set; }

        [EdiValue("X(48)", Path = "LIN/26", Description = "LIN27 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID13 { get; set; }

        [EdiValue("X(2)", Path = "LIN/27", Description = "LIN28 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier14 { get; set; }

        [EdiValue("X(48)", Path = "LIN/28", Description = "LIN29 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID14 { get; set; }

        [EdiValue("X(2)", Path = "LIN/29", Description = "LIN30 - Product/Service ID Qualifier")]
        [EdiExtension(MinLength = 2, MaxLength = 2, Mandatory = false, EdiType = EdiType.Identifier)]
        [EdiAllowValue(AllowedValues = new string[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "BA", "BB", "BC", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BK", "BL", "BM", "BN", "BO", "BP", "BQ", "BR", "BS", "BT", "BU", "BV", "BW", "BX", "BY", "BZ", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "CA", "CB", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ", "CK", "CL", "CM", "CN", "CO", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CW", "CX", "CY", "CZ", "D1", "D2", "D3", "D4", "D5", "DD", "DE", "DF", "DG", "DI", "DL", "DM", "DN", "DO", "DP", "DQ", "DR", "DS", "DT", "DU", "DV", "DW", "DX", "DY", "DZ", "E1", "E2", "E3", "E4", "E5", "E6", "EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH", "EI", "EJ", "EK", "EL", "EM", "EN", "EP", "EQ", "ER", "ES", "EU", "EX", "EZ", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "FA", "FB", "FC", "FD", "FE", "FF", "FG", "FI", "FL", "FM", "FN", "FP", "FS", "FT", "FW", "GA", "GC", "GD", "GE", "GI", "GK", "GN", "GQ", "GR", "GS", "GU", "HC", "HD", "HI", "HN", "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IM", "IN", "IP", "IQ", "IR", "IS", "IT", "IV", "IW", "IZ", "JA", "JB", "JC", "JD", "JN", "JP", "JS", "KA", "KB", "KD", "KE", "KF", "KG", "KI", "KJ", "KK", "KL", "KM", "KN", "KP", "L1", "L2", "L3", "L4", "L5", "LA", "LB", "LC", "LD", "LG", "LP", "LR", "LS", "LT", "LU", "MA", "MB", "MC", "MD", "ME", "MF", "MG", "MH", "MI", "MJ", "MK", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "N1", "N2", "N3", "N4", "N5", "N6", "NC", "ND", "NE", "NH", "NM", "NR", "NU", "NW", "NZ", "OA", "OB", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OL", "ON", "OO", "OP", "OR", "OT", "P1", "P2", "P3", "P4", "P5", "P7", "P8", "P9", "PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "PZ", "R1", "R2", "RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RR", "RS", "RT", "RU", "RV", "RW", "RY", "RZ", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY", "SZ", "T2", "T3", "TA", "TB", "TC", "TD", "TE", "TF", "TG", "TH", "TI", "TJ", "TM", "TN", "TP", "TR", "TS", "TT", "TU", "TV", "TW", "TX", "TY", "TZ", "U2", "U3", "U5", "U6", "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UH", "UI", "UJ", "UK", "UL", "UM", "UN", "UO", "UP", "UQ", "UR", "US", "UT", "UV", "UX", "VA", "VB", "VC", "VE", "VI", "VM", "VN", "VO", "VP", "VS", "VT", "VU", "VV", "VX", "W1", "W2", "W5", "W6", "W7", "WA", "WC", "WL", "WR", "WS", "XA", "XC", "XP", "XQ", "XZ", "YP", "ZB", "ZR", "ZZ" })]

        public string ProductOrServiceIDQualifier15 { get; set; }

        [EdiValue("X(48)", Path = "LIN/30", Description = "LIN31 - Product/Service ID")]
        [EdiExtension(MinLength = 1, MaxLength = 48, Mandatory = false, EdiType = EdiType.Alphanumeric)]
        public string ProductOrServiceID15 { get; set; }
    }
}
